version: '3.7'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_DATABASE=mobile-ecommerce
      - DB_PORT=5432
      - DB_MIGRATION_FOLDER=file://sql/migrations

  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=mobile-ecommerce
volumes:
  data:
